#!/usr/bin/env node

var program = require('commander');
var fs = require('fs');
var avn = require('..');

program
  .version(JSON.parse(fs.readFileSync(__dirname + '/../package.json', 'utf8')).version)
  .command('setup')
  .description('setup avn')
  .action(function() {
    avn.setup().done();
  });

program.parse(process.argv);
